### ISSUE TITLE
这个总资产跟余额怎么查询呢?

### ISSUE THREAD

**Issue by chenzz66** [DywaneQ/ETHWallet#10]

**Comment by DwyaneQ** [comment]
Duplicate of #9 //建立连接

Admin web3j = AdminFactory.build(new HttpService("你自己站点的地址"));

//获取指定钱包的比特币余额

BigInteger integer=web3j.ethGetBalance(“钱包地址”,DefaultBlockParameterName.LATEST).send().getBalance();

//获取指定钱包的指定币种余额

value=web3j.ethCall(Transaction.createEthCallTransaction(“钱包地址”,”代币地址”, “交易串”),DefaultBlockParameterName.PENDING).send().getValue();
最近比较忙，你先参考一下，还是基于web3j

**Comment by chenzz66** [comment]
恩恩,明白了  谢谢!!!!
