### ISSUE TITLE
INSTALL_FAILED_NO_MATCHING_ABIS

### ISSUE THREAD

**Issue by ilkeew** [DywaneQ/ETHWallet#14]
android8.0以上 bitcoinj依赖库  提示INSTALL_FAILED_NO_MATCHING_ABIS，8.0以下运行正常

**Comment by DwyaneQ** [comment]
可能跟bitcoinj 支持的CPU架构有关，请问您运行的设备是什么架构的？

**Comment by ilkeew** [comment]
我最终的解决方案是
    implementation('org.bitcoinj:bitcoinj-core:0.14.3') {
        exclude module: 'scrypt'
    }
忽略里面的module

**Comment by DwyaneQ** [comment]
好的，确实，用到bitcoinj主要还是助记词生成的算法部分

**Comment by ilkeew** [comment]
demo很强势啊  给你点赞
