### ISSUE TITLE
怎么将私钥转换为助记词

### ISSUE THREAD

**Issue by CaptainJno** [DywaneQ/ETHWallet#3]
请教一下怎么将私钥转换为助记词，有没有简洁的方法，比如传入一个私钥，返回助记词
现在代码不完善，有问题：以私钥方式导入的钱包，导出助记词时为空。

**Comment by DywaneQ** [comment]
创建钱包的时候，是通过BIP44生成助记词，再由助记词生成私钥。但是导入钱包的时候暂时没法通过私钥逆推助记词，你可以参考一下imToken和MyEtherWallet通过私钥导入钱包的功能。

**Comment by DywaneQ** [comment]
创建钱包的时候，是通过BIP44生成助记词，再由助记词生成私钥。但是导入钱包的时候暂时没法通过私钥逆推助记词，你可以参考一下imToken和MyEtherWallet通过私钥导入钱包的功能。

**Comment by CaptainJno** [comment]
“暂时没法通过私钥逆推助记词”是指你暂时还没写这块代码，还是说相关协议不支持呢？

**Comment by CaptainJno** [comment]
再请教一个问题，想向大神学习。比如说导入助记词生成私钥这个功能，你是怎么琢磨出来的呢？我看了网上的一些代码和文章还是没能写出来，最后参照大神你的代码才写出来了。

**Comment by DywaneQ** [comment]
是不支持，你试一下Jaxx、imToken这两个钱包，导入私钥的时候是没有助记词的，市面上的钱包都是通过BIP44这个标准生成的，所以就需要用到bitcoinj这个开发库，阅读一下官方文档，还有加密算法的相关文章。

**Comment by CaptainJno** [comment]
大佬能不能建个QQ群，方便大家一起沟通，一起研究探讨呀。
建好后可以在README公布一下群号码呀。
