### ISSUE TITLE
 Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

### ISSUE THREAD

**Issue by 337077418** [DywaneQ/ETHWallet#8]
试过了下面两种方法都不能安装：
1.File --->  Settings ---> Build,Execution,Deployment ---> Instant Run
把Enable Instant Run to选项去掉
2.splits {
    abi {
        enable true
        reset()
        include 'x86', 'armeabi-v7a','x86_64'
        universalApk true
    }
}

**Comment by DywaneQ** [comment]
请问你的设备是什么型号的？

**Comment by 337077418** [comment]
Mac上Studio的模拟器CPU是X86的

**Comment by DwyaneQ** [comment]
@337077418 可能不支持x86架构下的设备，我在真机上跑都没问题，你看看换成arm架构的模拟器呢

**Comment by 337077418** [comment]
感谢回复

**Comment by QuincySx** [comment]
我用高通真机也是这个错误

**Comment by qq451682583** [comment]
我用华为META9 真机 也是这个错误
